<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:include filename="consts.xacro"/>  
    <xacro:include filename='inertial_macros.xacro'/>

    <!-- Limits -->
    <xacro:macro name="hip_limits">
        <limit lower="${hip_low_limit}" upper="${hip_high_limit}" velocity="${velocity}" effort="${effort}"/>
    </xacro:macro>
    <xacro:macro name="knee_limits">
        <limit lower="${knee_low_limit}" upper="${knee_high_limit}" velocity="${velocity}" effort="${effort}"/>
    </xacro:macro>

    <!-- *********** base link *********** -->
    <link name="base_link"></link>

    <link name="chassis_link">
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </collision>
    </link>

    <!-- imu -->
    <link name="imu_link">
        <xacro:inertial_box mass="${imu_mass}" x="${imu_length}" y="${imu_width}" z="${imu_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}"/>
            </geometry>
            <material name="white"/>
        </collision>
    </link>
    
    <!-- hips -->
    <link name="left_hip_link">
        <visual>
            <origin xyz="0 0 -${rod_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 -${rod_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
            <origin xyz="0 0 -${rod_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <link name="right_hip_link">
        <visual>
            <origin xyz="0 0 -${rod_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 -${rod_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
            <origin xyz="0 0 -${rod_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- knees -->
    <link name="left_knee_link">
        <visual>
            <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="orange"/>
        </collision>
        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
            <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <link name="right_knee_link">
        <visual>
            <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="orange"/>
        </collision>
        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
            <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- wheels -->

    <link name="left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <surface>
                <friction>
                    <ode>
                        <mu>1</mu>
                        <mu2>1</mu2>
                        <fdir1>1 0 0</fdir1>
                    </ode>
                </friction>
            </surface>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <link name="right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <surface>
                <friction>
                    <ode>
                        <mu>1</mu>
                        <mu2>1</mu2>
                        <fdir1>1 0 0</fdir1>
                    </ode>
                </friction>
            </surface>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- chassis_joint -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
    </joint>

    <!-- imu joint -->
    <joint name="imu_joint" type="fixed">
        <origin xyz="0.0 0.0 ${chassis_height/2 + imu_height/2}" rpy="0.0 0.0 0.0"/>
        <parent link="chassis_link"/>
        <child link="imu_link"/>
    </joint>

    <!-- hip joints -->
    <joint name="left_hip_joint" type="revolute">
        <origin xyz="0.0 ${chassis_width/2 + rod_width/2} 0.0" rpy="0.0 ${3.142/2} 0.0"/>
        <parent link="chassis_link"/>
        <child link="left_hip_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <xacro:hip_limits></xacro:hip_limits>
        <xacro:if value="${use_dynamics}">
            <xacro:hip_joint_dynamics></xacro:hip_joint_dynamics>
        </xacro:if>
    </joint>

    <joint name="right_hip_joint" type="revolute">
        <origin xyz="0.0 -${chassis_width/2 + rod_width/2} 0.0" rpy="0.0 ${3.142/2} 0.0"/>
        <parent link="chassis_link"/>
        <child link="right_hip_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <xacro:hip_limits></xacro:hip_limits>
        <xacro:if value="${use_dynamics}">
            <xacro:hip_joint_dynamics></xacro:hip_joint_dynamics>
        </xacro:if>
    </joint>
    
    <!-- knee joints  -->

    <joint name="left_knee_joint" type="revolute">
        <origin xyz="0.0 ${rod_width} -${rod_height}" rpy="0.0 0.0 0.0"/>
        <parent link="left_hip_link"/>
        <child link="left_knee_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <xacro:knee_limits></xacro:knee_limits>
        <xacro:if value="${use_dynamics}">
            <xacro:knee_joint_dynamics></xacro:knee_joint_dynamics>
        </xacro:if>
    </joint>

    <joint name="right_knee_joint" type="revolute">
        <origin xyz="0.0 -${rod_width} -${rod_height}" rpy="0.0 0.0 0.0"/>
        <parent link="right_hip_link"/>
        <child link="right_knee_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <xacro:knee_limits></xacro:knee_limits>
        <xacro:if value="${use_dynamics}">
            <xacro:knee_joint_dynamics></xacro:knee_joint_dynamics>
        </xacro:if>
    </joint>

    <!-- wheel joints -->

    <joint name="left_wheel_joint" type="continuous">
      <origin xyz="0 ${wheel_length/2 + rod_length/2} ${rod_height}" rpy="${3.142/2} 0 0"/>
      <parent link="left_knee_link"/>
      <child link="left_wheel"/>
      <axis xyz="0.0 0.0 -1.0"/>
    </joint>

    <joint name="right_wheel_joint" type="continuous">
      <origin xyz="0 -${wheel_length/2 + rod_length/2} ${rod_height}" rpy="${3.142/2} 0 0"/>
      <parent link="right_knee_link"/>
      <child link="right_wheel"/>
      <axis xyz="0.0 0 -1.0"/>
    </joint>


</robot>
