controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: false

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_cont:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.329
    wheel_radius: 0.0855

    use_stamped_vel: false

joint_cont:
  ros__parameters:
    joints:
      - left_hip_joint
      - left_knee_joint
      - right_hip_joint
      - right_knee_joint
    
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

# Uncomment and configure if needed
joint_broad:
  ros__parameters:
    publish_rate: 50.0

    use_local_topics: true
