<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="Model_URDF">

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="wheel_radius" value="0.0855"/>
    <xacro:property name="wheel_length" value="0.045"/>
    
    <xacro:property name="wheel_mass" value="2.2"/>
    <xacro:property name="chassis_mass" value="2.0"/>
    <xacro:property name="rod_mass" value="1.0"/>

    <!-- Width, length, height = x,y,z -->
    <xacro:property name="chassis_length" value="0.2"/>
    <xacro:property name="chassis_width" value="0.15"/> 
    <xacro:property name="chassis_height" value="0.12"/> 

    <xacro:property name="rod_length" value="0.1"/>
    <xacro:property name="rod_width" value="0.01"/> 
    <xacro:property name="rod_height" value="0.2"/> 

    <xacro:property name="hip_offset_z" value="0"/>
    <xacro:property name="hip_offset_y" value="${chassis_width/2 + rod_width/2}"/>
    <xacro:property name="hip_offset_x" value="${rod_height/2}"/>

    <xacro:property name="knee_offset_z" value="0.0"/>
    <xacro:property name="knee_offset_y" value="${chassis_width/2 + rod_width/2}"/>
    <xacro:property name="knee_offset_x" value="${rod_height}"/>

    <xacro:property name="wheel_offset_x" value="${rod_height}"/>
    <xacro:property name="wheel_offset_y" value="0"/>
    <xacro:property name="wheel_offset_z" value="${wheel_radius/2}"/>

    <link name = "base_link">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="chassis_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="chassis"/>
    </joint>

    <link name="chassis">

        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>

        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length -0.01} ${chassis_width-0.01} ${chassis_height-0.01}"/>
            </geometry>
            <material name="orange"/>
        </collision>

    </link>

    <link name="left_hip">

        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
            <origin xyz="${hip_offset_x} 0 0" rpy="1.5708 0 -1.5708"/>
        </xacro:inertial_box>

        <visual>
            <origin xyz="${hip_offset_x} 0.0 0.0" rpy="1.5708 0 -1.5708"/>            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="${hip_offset_x} 0.0 0.0" rpy="1.5708 0 -1.5708"/>
            <geometry>
                <box size="${rod_length -0.01} ${rod_width -0.01} ${rod_height -0.02}"/>
            </geometry>
            <material name="blue"/>
        </collision>

    </link>

    <joint name="left_hip_joint" type="revolute">
      <origin xyz="0 ${hip_offset_y} 0" rpy="-1.5708 1.5708 0"/>
      <parent link="chassis"/>
      <child link="left_hip"/>
      <axis xyz="0 0 1.0"/>
      <limit lower="-1.5708" upper="0.0" effort="35.0" velocity="5.0"/>
    </joint>

    <link name="left_knee">

        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
            <origin xyz="${knee_offset_x/2} 0 0" rpy="1.5708 0 -1.5708"/>
        </xacro:inertial_box>

        <visual>
            <origin xyz="${knee_offset_x/2} 0.0 0.0" rpy="1.5708 0 -1.5708"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="${knee_offset_x/2} 0.0 0.0" rpy="1.5708 0 -1.5708"/>
            <geometry>
                <box size="${rod_length -0.01} ${rod_width -0.01} ${rod_height -0.02}"/>
            </geometry>
            <material name="blue"/>
        </collision>

    </link>

    <joint name="left_knee_joint" type="revolute">
      <origin xyz="${knee_offset_x} 0 0" rpy="0 0 -1.5708"/>
      <parent link="left_hip"/>
      <child link="left_knee"/>
      <axis xyz="0 0 1.0"/>
      <limit lower="-3.142" upper="-2.0" effort="35.0" velocity="5.0"/>
    </joint>

    <link name="left_wheel">
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>

        <visual>
            <origin xyz="0 0.0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius-0.01}" length="${wheel_length-0.01}"/>
            </geometry>
            <material name ='white' />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius-0.01}" length="${wheel_length-0.01}"/>
            </geometry>
            <material name ='white' />
        </collision>
    </link>

    <joint name="l_wheel_joint" type="continuous">
      <origin xyz="${wheel_offset_x} 0 ${wheel_offset_z}" rpy="0 0 -1.5708"/>
      <parent link="left_knee"/>
      <child link="left_wheel"/>
      <axis xyz="0 0 1.0"/>
    </joint>

    <link name="right_hip">

        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
            <origin xyz="${hip_offset_x} 0 0" rpy="1.5708 0 -1.5708"/>
        </xacro:inertial_box>

        <visual>
            <origin xyz="${hip_offset_x} 0.0 0.0" rpy="1.5708 0 -1.5708"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="${hip_offset_x} 0.0 0.0" rpy="1.5708 0 -1.5708"/>
            <geometry>
                <box size="${rod_length-0.01} ${rod_width-0.01} ${rod_height-0.02}"/>
            </geometry>
            <material name="blue"/>
        </collision>

    </link>

    <joint name="right_hip_joint" type="revolute">
      <origin xyz="0 -${hip_offset_y} 0" rpy="-1.5708 1.5708 0"/>
      <parent link="chassis"/>
      <child link="right_hip"/>
      <axis xyz="0 0 1.0"/>
      <limit lower="-1.5708" upper="0.0" effort="35.0" velocity="5.0"/>
    </joint>

    <link name="right_knee">

        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
            <origin xyz="${knee_offset_x/2} 0 0" rpy="1.5708 0 -1.5708"/>
        </xacro:inertial_box>

        <visual>
            <origin xyz="${knee_offset_x/2} 0.0 0.0" rpy="1.5708 0 -1.5708"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="${knee_offset_x/2} 0.0 0.0" rpy="1.5708 0 -1.5708"/>
            <geometry>
                <box size="${rod_length-0.01} ${rod_width-0.01} ${rod_height-0.02}"/>
            </geometry>
            <material name="blue"/>
        </collision>

    </link>

    <joint name="right_knee_joint" type="revolute">
      <origin xyz="${knee_offset_x} 0 0" rpy="0 0 -1.5708"/>
      <parent link="right_hip"/>
      <child link="right_knee"/>
      <axis xyz="0 0 1.0"/>
      <limit lower="-3.142" upper="-2.0" effort="35.0" velocity="5.0"/>
    </joint>

    <link name="right_wheel">
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>

        <visual>
            <origin xyz="0 0.0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius-0.01}" length="${wheel_length-0.01}"/>
            </geometry>
            <material name ='white' />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius-0.01}" length="${wheel_length-0.01}"/>
            </geometry>
            <material name ='white' />
        </collision>
    </link>

    <joint name="r_wheel_joint" type="continuous">
      <origin xyz="${wheel_offset_x} 0 -${wheel_offset_z}" rpy="0 0 -1.5708"/>
      <parent link="right_knee"/>
      <child link="right_wheel"/>
      <axis xyz="0 0 -1.0"/>
    </joint>

</robot>